server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      # consul注册中心地址
      host: 192.168.200.132
      port: 8500
      discovery:
        register: false


