server:
  port: 7002

spring:
  application:
    name: cloud-eureka-server7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    fetch-registry: false  #不注册自己
    register-with-eureka: false # 不检索自己
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
