server:
  # consul服务端口
  port: 8006
spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      # consul注册中心地址
      host: 192.168.200.132
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
        register-health-check: true
        health-check-path: /actuator/health
        health-check-interval: 10s